### ISSUE TITLE
Add Support For QueryDict Lists

### ISSUE THREAD

**Issue by mpistrang** [jacobb/nap#23]
Please add support for passing a list as a query string param.

I would like to be able to call a url with the following query string:

http://myurl.com/myresource/?animals=DOGS&animals=CATS&colors=BROWN"

resulting in Querydict() d for which the following would be true.

d.getlist('animals') == ['DOGS,'CATS']
d.getlist('colors') == ['BROWN']

**Comment by jacobb** [comment]
Fixed
